import { type Book } from "../components/BookCard";

export const books: Book[] = [
  {
    title: "Me and the Temple of Earth",
    titleCn: "我与地坛",
    slug: "me-and-the-temple-of-earth",
    author: "Shi Tiesheng",
    authorCn: "史铁生",
    status: "Reading",
    image: "/covers/s6313029.jpg",
    note: "A contemplative essay about life, disability, and finding meaning in an ancient Beijing park.",
    noteCn: "关于生命、残疾与在北京古老公园中寻找意义的沉思散文。",
    link: "https://www.goodreads.com/book/show/18048869",
    linkCn: "https://book.douban.com/subject/6079389/",
  },
  {
    title: "Steppenwolf",
    titleCn: "荒原狼",
    slug: "steppenwolf",
    author: "Hermann Hesse",
    authorCn: "赫尔曼·黑塞",
    status: "Wishlist",
    image: "/covers/s3286369.jpg",
    note: "A exploration of duality and alienation through the story of a man torn between his human and wolf natures.",
    noteCn: "通过一个在人性与狼性之间挣扎的男人的故事，探索二元性与疏离感。",
    link: "https://www.goodreads.com/book/show/16631.Steppenwolf",
    linkCn: "https://book.douban.com/subject/3131626/",
  },
  {
    title: "Siddhartha",
    titleCn: "悉达多",
    slug: "siddhartha",
    author: "Hermann Hesse",
    authorCn: "赫尔曼·黑塞",
    status: "Finished",
    image: "/covers/s29396368.jpg",
    note: "A spiritual journey of self-discovery through the life of a young man in ancient India.",
    noteCn: "一个年轻人在古印度的自我发现与精神之旅。",
    link: "https://www.goodreads.com/book/show/52036.Siddhartha",
    linkCn: "https://book.douban.com/subject/26980487/",
  },
  {
    title: "Life and Death Are Wearing Me Out",
    titleCn: "生死疲劳",
    slug: "life-and-death",
    author: "Mo Yan",
    authorCn: "莫言",
    status: "Finished",
    image: "/covers/s35289336.jpg",
    note: "A landowner's six reincarnations witness half a century of rural China through the eyes of animals.",
    noteCn: "一个地主经历六道轮回，以动物视角见证中国农村半个世纪的变迁。",
    link: "https://www.goodreads.com/book/show/19172190",
    linkCn: "https://book.douban.com/subject/35587028/",
  },
];
